### ISSUE TITLE
Plans for BLOM/iHAMOCC for NorESM2.5

### ISSUE THREAD

**Issue by TomasTorsvik** [NorESMhub/BLOM#340]
Tentative plans for default (and optional) settings for BLOM/iHAMOCC towards NorESM2.5
See also #438 

- We will keep the MCT support until the technical release of NorESM2.5 (https://github.com/NorESMhub/BLOM/issues/439) 

- cgs units support will phase out - likely keep unit support for the restart files reading to enable restart from former restart files

- Plans for further development have been moved to a new overview issue: #462 
 

### Planning for release-1.7

Tasks under this heading can go into a new `release-1.7`, and will be carried forward into NorESM2.5.

**BLOM-specific**
- [x] BLOM code refactorization
- [x] hybrid coordinates (default) (isopycnal optional)
- [x] Add 2 degree grid resolution
- [x] Add 1/2 degree grid resolution
- [x] Fix some blom tnx2v1 namelist parameters #463 
- [x] support git fleximod #465 and #466 

**iHAMOCC-specific**
- [x] (potentially) making output files more cdo-compatible #355
- [x] Potentially remove separation of processes into euphotic and non-euphotic zone processes - refer to #365 and #367 
- [x] Make preformed tracers optional - to enable switching them off for HR runs - done via #394
- [x] Remove the option to run cyanobacteria (bluefix) in the MLD (default remains to run them in the euphotic zone) - see #395 and #396
- [x] bugfix sediment extended N-cycle #413 
- [x] dust flux to sediment output #420
- [x] Unify N-deposition reading - done with #410 (for nuopc) - see #397 and #398 for some further discussion. For post- BLOM tag v1.6.x simulations, nuopc is expected to handle the input, while for tag v1.6.x simulations with the extended nitrogen cycle switched on, a limited set of input files are generated by @jmaerz (request in case of interest)
- [x] Make i) T-dep. and ii) O2-dep. of remineralization available to default model code via thus far optional switch- see #400 and #424 , where the first step with a switch is taken  for the water column - sediment thus far missing (only realized for the extended N cycle) - #454 
- [x] #449
- [x] New tag for M4AGO  #460
- [x] Update POC remin rate in sediment #461 and #464

**Comment by jmaerz** [comment]
**iHAMOCC-specific**

- [ ] Cold start of preformed (silicate) tracer  - handle all preformed tracers equally

**Comment by TomasTorsvik** [comment]
This should maybe go into the milestone description at some point. Just edit the first entry if you have more things to add.

**Comment by mvertens** [comment]
@TomasTorsvik @matsbn @JorgSchwinger @jmaerz - some of these tasks will no longer be needed once we use the new stream functionality in BLOM. In particular you will not need separate datasets for 2 degree and 1/2 degree. I hope to start implementing this next week. We had decided to move ahead with the 1/2 degree using the older approach since simulations were going to being very soon and we did not want the new implementation holding up the science. However, I hope to have this in place so that we don't need to generate new datasets for 2 degrees and then hopefully move all the resolutions to just interpolation from the original source. At least that is what I think that @matsbn was leaning towards.

**Comment by TomasTorsvik** [comment]
The release for NorESM2.5 has been pushed forward, so `v1.7.0` will now be the intended release tag for NorESM2.5.
